# Generated by Django 3.2.5 on 2021-07-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='status',
            field=models.IntegerField(choices=[(1, 'new'), (2, 'in progress'), (3, 'done')], default=1),
        ),
    ]
